version: "3.9"

services:
  app:
    container_name: desafio-itau-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      ESTATISTICA_SEGUNDOS: 60
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
